export const QUICK_ACTION_PROMPTS = [
  "A flying rocket with fire trail",
  "An animated triangle loader",
  "A minimalist mountain sunset",
  "A cute robot waving",
  "A glassmorphism credit card",
  "A neon cyberpunk city skyline",
  "A flat design coffee cup with steam",
  "A 3D isometric house",
  "A set of social media icons",
  "A futuristic weather widget",
  "A geometric fox logo",
  "A colorful tropical parrot",
  "A sleek dark mode dashboard UI",
  "A vintage postage stamp",
  "A sci-fi glowing portal",
  "A floating island with a waterfall",
  "A simple line-art cat",
  "A high-tech circuit board pattern",
  "A stack of colorful books",
  "A stylized paper plane",
  "A friendly ghost animation",
  "A retro game controller",
  "A modern abstract logo",
  "A lighthouse in a storm",
];
